---

formatter: ""  # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: examples

sections:
  hide: []
  show: []

content: |-

  {{ .Header }}

  ## Basic example

  ```hcl
  terraform {
    required_version = ">= 1.10.0"
    required_providers {
      azurerm = {
        source  = "hashicorp/azurerm"
        version = "~> 4.0"
      }
    }
  }

  provider "azurerm" {
    features {}
  }

  resource "azurerm_resource_group" "vmss" {
    name     = "rg-vmss-example"
    location = "uksouth"
  }

  resource "azurerm_virtual_network" "vmss" {
    name                = "vnet-vmss-example"
    resource_group_name = azurerm_resource_group.vmss.name
    address_space       = ["10.0.0.0/16"]
    location            = azurerm_resource_group.vmss.location
  }

  resource "azurerm_subnet" "agents" {
    name                 = "snet-vmss-agents"
    resource_group_name  = azurerm_resource_group.vmss.name
    address_prefixes     = ["10.0.1.0/24"]
    virtual_network_name = azurerm_virtual_network.vmss.name
  }

  module "vmss" {
    source  = "tonyskidmore/vmss/azurerm"
    version = "~> 1.0"

    vmss_name                = "vmss-example"
    vmss_resource_group_name = azurerm_resource_group.vmss.name
    vmss_subnet_id           = azurerm_subnet.agents.id
    vmss_admin_password      = var.vmss_admin_password
  }
  ```
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Footer }}


output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
