---

formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: [ ]
  show: [ ]

content: |-

  {{ .Header }}

  Azure Virtual Machine Scale Set Terraform module.
  It is a single resource module, with opinionated defaults and forms the starting point
  for the creation of an
  [Azure virtual machine scale set agent](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents) pool in Azure DevOps.

  ## Basic example

  ```hcl

  {{ include "examples/example1/main.tf" }}

  ```
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Footer }}


output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
