---

name: Lint Code Base

on:
  workflow_dispatch:
  pull_request:
  push:
    # paths-ignore:
    #   - 'README.md'
    #   - 'CHANGELOG.md'
    # branches:
    #   - main


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list
          # of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install Python packages
        run: pip install -r dev-requirements.txt

        # https://github.com/marketplace/actions/super-linter
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use pre-commit to fix newly generated data files
        # if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: |
          pre-commit install
          pre-commit install-hooks
          pre-commit run --all || pre-commit run --all
